### ISSUE TITLE
Mark active links in `nav-main` partial

### ISSUE THREAD

**Issue by hugurp** [internet4000/portfolio-hugo-theme#4]
When the user is on home, which is projects, or on contact, the page link should have an acive class of `is-active`.

**Comment by oskarrough** [comment]
Something like this

```
{{ $currentPage := . }}
{{ range $index, .Site.Menus.main }}
	<a class="{{if or ($currentPage.IsMenuCurrent "main" .) ($currentPage.HasMenuCurrent "main" .) }} active{{end}}" href="{{.URL}}">
		{{ .Name }}
	</a>
{{ end }}
```

can't make line-breaks for readability because it'll break hugo templating...

**Comment by oskarrough** [comment]
Also, let's use the hugo menu system? So you can control the menu without fiddling around in templates.
