### ISSUE TITLE
nav-main — generate dynamically

### ISSUE THREAD

**Issue by hugurp** [internet4000/portfolio-hugo-theme#7]
Right now the navigation is semi-static semi-dymanic.

It uses the `partial/nav-main.html` file, but only generates menu items for pages of type `page`.

It should:
- [ ] generate links to the root of all hugo `sections`, the folders defined inside `c/ontent`

**Comment by oskarrough** [comment]
To generate the section menu: https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
